( cd org.metaborg.mbt.core ; mvn clean install )
( cd org.metaborg.spt.core ; mvn clean install )
( cd org.metaborg.meta.lang.spt ; mvn clean install )
( cd org.metaborg.meta.lang.spt.eclipse ; mvn clean install )
( cd org.metaborg.meta.lang.spt.interactive ; mvn clean install )
( cd org.metaborg.meta.lang.spt.interactive.eclipse ; mvn clean install )
